export default{
  MARK_NOTIFY_AS_BY_ID: 'MARK_NOTIFY_AS_BY_ID',
  MARK_ALL_NOTIFY: 'MARK_ALL_NOTIFY',
  START_MARK_AS_READ: 'START_MARK_AS_READ',
  FINISH_MARK_AS_READ: 'FINISH_MARK_AS_READ',
  RECIVED_NOTIFY_LIST: 'RECIVED_NOTIFY_LIST',
  START_LOGIN: 'START_LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILD: 'LOGIN_FAILD',
  CHANGE_AVATAR: 'CHANGE_AVATAR'
}